name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore        
    - name: Install SonarCloud scanner           
      run: dotnet tool install --global dotnet-sonarscanner        
    - name: Sonarqube Start
      run: dotnet sonarscanner begin /k:"olakara_fluffy-barnacle" /o:"olakara" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
    - name: Build Project
      run: dotnet build --no-restore -c Release 
    - name: Test Project
      run: dotnet test --no-build --verbosity normal
    - name: Sonarqube End
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    - name: Publish Project
      run: dotnet publish -c Release -o publish
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: olakara/fluffy-barnacle
        registry: docker.io        
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

