name: Build & Publish Application

on:
  push:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          # Disabling shallow clone is recommended for improving relevancy of sonarqube reporting
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore        
    - name: Install SonarCloud scanner           
      run: dotnet tool install --global dotnet-sonarscanner        
    - name: Sonarqube Start      
      run: dotnet sonarscanner begin /k:"olakara_fluffy-barnacle" /o:"olakara" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
    - name: Build Project
      run: dotnet build --no-restore -c Release 
    - name: Test Project
      run: dotnet test --collect:"XPlat Code Coverage" --logger:trx --verbosity normal  -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    - name: Sonarqube End
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}" 
    - name: Publish
      run: dotnet publish ./src/fluffy-barnacle.csproj -c Release -o publish
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: olakara/fluffy-barnacle
        registry: docker.io
        addLatest: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

